### ISSUE TITLE
Creating Data obj, L

### ISSUE THREAD

**Issue by akhst7** [csoneson/conquer_comparison#13]
I can't find  L, a data obj used in the almost all the apply- method in the repository.  It will great if you could post it or a script used to generate L posted in the repository.

Thanks.

**Comment by csoneson** [comment]
The `apply_*` scripts are not run directly, but called from the `run_diffexpression.R` script. See e.g. here: 
https://github.com/csoneson/conquer_comparison/blob/3c93f778639ec02c7c5324acddc968529c6c15ee/Makefile#L305-L309
That is also where the list `L` is created: 
https://github.com/csoneson/conquer_comparison/blob/3c93f778639ec02c7c5324acddc968529c6c15ee/scripts/run_diffexpression.R#L48-L49 
using the functions defined in https://github.com/csoneson/conquer_comparison/blob/master/scripts/prepare_mae.R

**Comment by csoneson** [comment]
I'm closing this issue - feel free to re-open if you have remaining questions about this.

**Comment by akhst7** [comment]
@csoneson, sorry about that, and thanks for closing !!
