### ISSUE TITLE
powsim and .rds formatting

### ISSUE THREAD

**Issue by yonchoi** [csoneson/conquer_comparison#2]
Thank you for this great work, I expect it will save people like me a lot of time on testing out differential analysis method. 

I was trying to just run this code on the provided data, but I am running into few issues.

First of all, I can't seem to install powsim as one of its dependencies, gu-mi/NBGOF cannot be installed due to ELF header error. Instead, I installed powsimR, powsim's update, which only runs on 3.4.0 or newer versions of R. As such, running powsimR introduces another issue of opening rds file, which I presume was created in R version 3.3.2, in R version 3.4.0. Using readRDS on the config$mae produces error stating the RDS file is outdated and suggests using updatedObject function. However, using updatedObject after readRDS results in an error below.

Error in validObject(.Object) : 
   class “MultiAssayExperiment” object: 'sampleMap' assay column not a factor

Please let me know if you know a fix to either installing powsim, or loading provided rds data in newer versions of R. 

Additionally, I could not install two additional packages, DEsingle and NODES. These are two of the methods that are being tested, but I cannot find sources that has these packages. 

Thank you for reading.

**Comment by csoneson** [comment]
Thank you for your interest in our work. A couple of suggestions that might help:

- Regarding the installation of the original version of powsim, I suggest you bring it up with the powsim developers. As far as I can see, there are a number of differences between powsim and powsimR, and I can not guarantee that our code will work as-is with powsimR. 
- The MultiAssayExperiment objects were indeed created with R 3.3.2. However, you can download updated objects from conquer (http://imlspenticton.uzh.ch:3838/conquer/) for most of the data sets. 
- The "assay column not a factor" error is related to a change in the validity checks in the MultiAssayExperiment package (https://github.com/waldronlab/MultiAssayExperiment/issues/206). If you explicitly turn the column into a factor I think it should work (see e.g. https://github.com/csoneson/conquer_comparison/blob/master/scripts/prepare_mae.R)
- You can get DEsingle here: https://github.com/miaozhun/DEsingle
- NODES is provided as an archive by the authors (link from their bioRxiv preprint: https://www.dropbox.com/s/pno78mmlj0exv7s/NODES_0.0.0.9010.tar.gz?dl=0)

Hope this helps
Charlotte
