### ISSUE TITLE
Add a new DE method

### ISSUE THREAD

**Issue by blueskypie** [csoneson/conquer_comparison#4]
To create a new `Apply_*.R`, what should be the return value of the method? I see that those `Apply_*.R` returns a `list(session_info,timing, res, df)`, what should be the content of the `res`?

Thanks a lot!

**Comment by csoneson** [comment]
The required elements (that will be used later, see https://github.com/csoneson/conquer_comparison/blob/master/scripts/prepare_cobra_for_evaluation.R) are `timing` and `df`. `res` (sometimes missing, sometimes differently named) just stores the raw result output from the respective methods, for completeness. It can have different formats for different methods, and can be useful if you later want to look at aspects of the results that are not included in `df`.

**Comment by blueskypie** [comment]
Thanks for the quick response!
