### ISSUE TITLE
Difficulty in running the script

### ISSUE THREAD

**Issue by blueskypie** [csoneson/conquer_comparison#5]
I'm trying to run the Makefile, but there are lots of issues. Could you update the script to R3.5 or provide a docker image of your working environment? Also, can you provide a testing `include_datasets.mk` containing minimum amount of datasets to test the Makefile?

Here are some issues:

1. Under R3.3, it's very difficult to install some packages; for example, "SingleCellExperiment". Even its [old version](https://bioarchive.galaxyproject.org/#/pkg/SingleCellExperiment/) requires R>=3.4. Some packages reside only in github and do not provide old versions compatible with R3.3
2. Since your scripts were written, some packages have changed their name; for example, powsim is now powsimR. And some packages have changed their function parameters or return values. 
3. The provided [data bundle](http://imlspenticton.uzh.ch/robinson_lab/conquer_de_comparison/Soneson_datasets.tar.gz) does not have some of the text files required by the Makefile. And the RDS files do not work with new version of MultiAssayExperiment, for example, on the pData slot.

**Comment by csoneson** [comment]
Thank you for posting this issue. We apologize for forgetting to include an important piece of information in the README of this repository (this has now been corrected): the purpose of the `conquer_comparison` repository is to provide a public record of the exact code that was used for our publication (Soneson & Robinson, Nature Methods 2018). In particular, it is not intended to be a software package or a general pipeline for differential expression analysis of single-cell data. As a consequence, running the code requires the same software and package versions that were used for our analyses (all versions are indicated in the paper). As the analysis involved running a large number of methods on many data sets and over an extended period of time, we cannot guarantee that it will run successfully with new releases of the software, or that exactly the same results will be obtained with newer versions of the packages. While the repository will not be updated to ensure that it runs with every new version of the used packages, the issues can be used to post questions and/or solutions as they arise. 

Regarding your specific issues:
1. We did not use the SingleCellExperiment package in our analysis for the paper. If you are applying a method that requires this package, you have to run it with a newer version of R than the one we used. The same is true for GitHub packages that require newer versions of R. 
2. The change from powsim to powsimR is not merely a change in name - the package is substantially revised (motivating the authors to make a completely new package), and thus there is no guarantee that our code would run as-is with the new package. As we describe above, the intention of this repository is not to provide a pipeline that will run with any new version of any of the packages, but to provide a record of the exact code that was used to generate the results in our paper. As methods are updated, we can not guarantee that exactly the same results would be obtained. 
3. Old MultiAssayExperiment objects can be updated using the updateObject() function provided in the MultiAssayExperiment package. The data bundle includes the data files generated by us, and the README provides the links to where all the other raw files were downloaded. 

Finally, please note that running the entire Makefile will take a very long time (likely weeks to months). Is your goal to include a new method in the comparison? We are working on other ways (likely an R data package) to distribute our data and results in a more accessible way to allow easier inclusion of additional methods. Would that be helpful to you? We can also share specific objects if that would be useful.

**Comment by blueskypie** [comment]
Thanks again for the info and quick response! Yes, we'd like to use your pipeline to compare our DE method with others. I understand that packages keep updating and it's difficult for you to maintain your code. One solution would be providing a docker images of working environment for uses to download.

**Comment by csoneson** [comment]
We will consider this. However, if I understand you correctly that wouldn't directly help in this case, since you use packages that require a newer version of R than we used (which would not be in the docker image). Until the data package I mentioned above is available, we are happy to share specific result objects from the methods we applied if that would be useful.

**Comment by blueskypie** [comment]
Thanks again! What I mean is to wrap everything, your OS, R, libraries, and file systems into a docker image, so the user can use your image directly without install anything additional. Another solution might be to create a public image on AWS that users can use to initiate a computing node to run their methods.

**Comment by csoneson** [comment]
Yes, that would help to rerun our methods (although it would likely take months to regenerate our results from scratch). But still, running another method that requires R3.5 would not really be directly helped by this as far as I can see. Including also the results in the image would of course help in the sense that it doesn’t require everything to be rerun. But providing the results in a package would help with this as well. We’ll think it over, thanks.

**Comment by blueskypie** [comment]
Thanks! Our method may be OK with R3.3. The reason I mention R3.5 is that I cannot install all the packages required by your pipeline with R3.3. Yes, I think it's a great idea to include the data and objects in the image so the `make` won't re-run them and only run new methods and data.

**Comment by kspham** [comment]
Dear Authors, 
Could you please release the docker so that we can reproduce the results?
Thank you so much!
Son

**Comment by csoneson** [comment]
In order to enable comparisons of new methods to the ones included in our paper, we have packaged all our differential expression results in an archive, accessible from http://imlspenticton.uzh.ch/robinson_lab/conquer_de_comparison/ (the data is also accessible from there). Unpacking this archive into a `results/` directory provides all the information that is necessary for the downstream analysis. As mentioned above, we don't recommend rerunning all the DE analyses, since this will likely correspond to months of computation time.
