### ISSUE TITLE
Prefiltering of lowly expressed genes 

### ISSUE THREAD

**Issue by shokohirosue** [csoneson/conquer_comparison#6]
In the paper, you described "prefiltering of lowly expressed genes" will improve edgeR/QLF method. Could you tell me what filtering criteria you applied to improve the results?

Thank you very much.

**Comment by csoneson** [comment]
See the Methods section in the paper/preprint:
> For each real and simulated data set, we perform the DE analysis evaluation both on the full, 'unfiltered', data set (excluding only genes with 0 counts in all considered cells) and on a filtered data set, where we retain only genes with an estimated TPM above 1 in more than 25% of the considered cells. Depending on the data set and the number of considered cells, between 4 and 50% of the genes are retained after this filtering (Supplementary Fig. 32).

**Comment by shokohirosue** [comment]
Thank you very much for your reply. I would like to apply this on 10X dataset where UMIs were used. Would you think CPM above 1 in more than 25% would do in this situation?

**Comment by csoneson** [comment]
We didn't explicitly optimize the filtering criteria in the paper, and the "best" filtering may very well depend on the data set, but yes, for the droplet data sets in our comparison we used a threshold of RPM (reads per million) above 1 in at least 25% of the cells.

**Comment by shokohirosue** [comment]
Thank you so much!

**Comment by ceesu** [comment]
Hello, I have a quick question about this. Besides filtering out genes that had zero counts across all samples, did you also filter out any of the cells you used for testing?

Related to this, I'm wondering how you ran DESeq2 specifically. It seems like for "the full, unfiltered, data set" this is handled through apply_DESeq2nofilt.R. For the other modes, it seems like TPM from EdgeR was used as input -- I'm wondering, did you use raw counts for the "nofilt" version?

Thank you.

**Comment by csoneson** [comment]
No, we don't explicitly filter the cells. 
The input to DESeq2 is the length-scaled TPM (calculated by tximport), which is on the scale of the raw counts. This is used as input for all DESeq2 modes. The "full, unfiltered data set" refers to the data set where we only filtered out genes that were zero across all samples, whereas the TPM values (from Salmon) are used to define the filtered data set. However, this is unrelated to the "DESeq2nofilt" - the latter just refers to running DESeq2 without the Cook's cutoff and without the independent filtering.

**Comment by ceesu** [comment]
Thanks for your reply. As a follow up, I'm wondering how close is the "full, unfiltered data set" to the raw data? It seems that the scripts were run separately on the unfiltered and filtered datasets in your paper. However when I try something similar with DESeq2 on my raw data, which contains a lot of 0-entries, there seem to be issues with computing size factors ( "every gene contains at least one zero, cannot compute log geometric means").

**Comment by csoneson** [comment]
Yes, the scripts are run separately on the unfiltered and filtered data sets (this preprocessing is done in the `subset_mae` function). The unfiltered data excludes just all-zero genes (see https://github.com/csoneson/conquer_comparison/blob/master/scripts/prepare_mae.R). 
For data with lots of zeros, you could try the `poscounts` normalization approach in `DESeq2` (see https://support.bioconductor.org/p/100201/).

**Comment by ceesu** [comment]
Thanks so much for your reply. I just have one last question. Is it correct that you only ever use TPMs for both the filtered and unfiltered data as input to all of the differential expression methods?

**Comment by csoneson** [comment]
The methods are provided with different types of input values depending on the underlying model (see Fig. 3 in the paper). The count-based methods, for example, don't get the TPMs, but the "length-scaled TPMs", generated by [tximport](https://bioconductor.org/packages/tximport/) (see also https://f1000research.com/articles/4-1521). These are on the scale of counts (e.g., the sum is equal to the number of assigned reads).

**Comment by ceesu** [comment]
I see, thank you very much!
