### ISSUE TITLE
Simulation method used for the signal datasets? 

### ISSUE THREAD

**Issue by ptdtan** [csoneson/conquer_comparison#7]
Dear Charlotte,

Thanks for your intensive work on the evaluation of DE methods. When reading the paper https://www.nature.com/articles/nmeth.4612, we found it unclear on how did you simulate the datasets with signals, which contain 10% DE genes. Could you describe it in details?

**Comment by csoneson** [comment]
I used the `powsim` package for the simulation, starting from three of the experimental data sets. The exact code I used is here: https://github.com/csoneson/conquer_comparison/blob/master/scripts/simulate_data.R

**Comment by kspham** [comment]
Do you have any description of that method in the paper?

**Comment by csoneson** [comment]
The approach is described in our Methods section:
> three of the data sets (GSE45719, GSE74596 and GSE60749-GPL13112) are used as the basis for simulation of data using a slightly modified version of the powsim R package34. Individual reports generated by countsimQC35 and verifying the similarity between the simulated and real data sets across a range of aspects are provided as Supplementary Data 1. As for the original, experimental data sets, we subsample data set instances with varying number of cells per group, and further generate null data sets by random sampling from one of the simulated groups. In each simulated data set, 10% of the genes are selected to be differentially expressed between the two groups, with fold changes sampled from a Gamma distribution with shape 4 and rate 2. The direction of the DE is randomly determined for each gene, with equal probability of up- and downregulation. Mean and dispersion parameters used as basis for the simulations are estimated from the respective real data sets using edgeR7. For each of the three data sets, the rounded length-scaled TPMs for all genes with at least two nonzero counts are used as input to the simulator, and a data set with the same number of genes is generated.

The code shows exactly which functions we ran, and with which parameters. 

The `powsim` paper describes their simulation model in more detail: https://www.biorxiv.org/content/10.1101/117150v1.full
