### ISSUE TITLE
Description of the results data

### ISSUE THREAD

**Issue by kspham** [csoneson/conquer_comparison#8]
Thank you very much for putting the results available to download: http://imlspenticton.uzh.ch/robinson_lab/conquer_de_comparison/ 

I would like to regenerate Fig.1 in your paper: https://www.nature.com/articles/nmeth.4612
It seems to me that the data of fig 1 is in the folder: conquer_comparison/results 
But in the results there are 1754 rds files, it's not clear for me how to generate Fig.1 from this result.

Could you clarify?

Thank you very much!

**Comment by csoneson** [comment]
You can find the entire procedure to generate the results in the Makefile: https://github.com/csoneson/conquer_comparison/blob/master/Makefile. The specific lines that generate Figure 1 are https://github.com/csoneson/conquer_comparison/blob/3c93f778639ec02c7c5324acddc968529c6c15ee/Makefile#L722-L730, which in turn assumes that you have run https://github.com/csoneson/conquer_comparison/blob/3c93f778639ec02c7c5324acddc968529c6c15ee/Makefile#L541-L549, following https://github.com/csoneson/conquer_comparison/blob/3c93f778639ec02c7c5324acddc968529c6c15ee/Makefile#L403-L428. All the scripts are also available in the GitHub repository.
